#!/bin/bash
cat<<EOF | ssh root@redwood.lab 
if [ ! -d .ssh ]; then mkdir .ssh ;fi
chmod 750 .ssh
ssh-keyscan -t dsa,rsa github.com > .ssh/known_hosts
ssh-keyscan -t dsa,rsa \$(dig +short github.com) >> .ssh/known_hosts
yum update -y
for pkg in httpd mod_perl mod_ssl git ;do
    rpm -qa | grep \$pkg || yum install -y \$pkg 
done

cp /etc/httpd/conf.d/ssl.conf /etc/httpd/conf.d/ssl.conf.dist
rpm -qa | grep autodir || (yum install -y autodir; /etc/init.d/autohome start)

grep PerlSwitches /etc/httpd/conf.d/ssl.conf || \
    awk '{
           if($0 == "<VirtualHost _default_:443>"){
               print "PerlSwitches -I/usr/share/pkild/lib";
               print "PerlModule pkild\n";
               print $0;
               print "<Location />"
               print "    SetHandler          modperl"
               print "    PerlResponseHandler pkild"
               print "</Location>" ;
           }else{ 
               print $0; 
           } 
         }' /etc/httpd/conf.d/ssl.conf.dist > /etc/httpd/conf.d/ssl.conf


try(){
    URI="\$*"
    FILE=\$(echo \$URI|sed -e 's/.*\///')
    wget -qO "\${FILE}" "\${URI}"
    rpm -Uvh "\${FILE}"
    if [ \$? -ne 0 ]; then
        rpm -Uvh "\${FILE}" 2>&1|grep "is needed"|sed -e 's/is needed.*//' -e 's/^[\t ]*//'|while read line; do
            yum install -y "\${line}" 2>&1 | grep "No package"
        done
    fi
}

try "http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-File-Modified-0.07-1.2.el5.rf.noarch.rpm"
try "http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-HTTP-Body-1.07-2.el5.rf.noarch.rpm"
try "http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Text-SimpleTable-2.03-1.el5.rf.noarch.rpm"
try "http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Tree-Simple-VisitorFactory-0.10-1.el5.rf.noarch.rpm"

yum install -y perl-YAML
yum install -y "perl(Class::Accessor::Fast)"
yum install -y "perl(Class::Data::Inheritable)"

yum install -y "perl(Data::OptList)"
yum install -y "perl(Params::Util)"
yum install -y "perl(Sub::Install)"
yum install -y "perl(Sub::Exporter)"

try "http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Object-Signature-1.05-1.el5.rf.noarch.rpm"
try "http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Sub-Exporter-0.982-1.el5.rf.noarch.rpm"
try "http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Try-Tiny-0.09-1.el5.rf.noarch.rpm"
try "http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Sub-Name-0.05-1.el5.rf.i386.rpm"
try "http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Devel-GlobalDestruction-0.02-1.el5.rf.i386.rpm"

yum install -y "perl(MRO::Compat)"
# try "http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Class-MOP-1.01-1.el5.rf.i386.rpm"
#     Couldn't load class (MooseX::Emulate::Class::Accessor::Fast) because:
#       Can't locate object method "get_mutable_metaclass_name"
#         via package "Class::MOP::Class::Immutable::Class::MOP::Class"
try http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Class-MOP-0.92-1.el5.rf.i386.rpm

yum install -y "perl(List::MoreUtils)"
yum install -y "perl(metaclass)"
# try "http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Moose-1.02-2.el5.rf.i386.rpm"
#     perl(Catalyst) <= 5.80017 conflicts with perl-Moose-1.02-2.el5.rf.i386
try http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Moose-0.89-2.el5.rf.noarch.rpm

try "http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Sub-Identify-0.04-1.el5.rf.i386.rpm"
try "http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Variable-Magic-0.46-1.el5.rf.i386.rpm"
try "http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-B-Hooks-EndOfScope-0.08-2.el5.rf.noarch.rpm"
try "http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-namespace-clean-0.13-1.el5.rf.noarch.rpm"
try "http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-MooseX-Emulate-Class-Accessor-Fast-0.00903-1.el5.rf.noarch.rpm"

yum install -y "perl(File::Copy::Recursive)"
yum install -y "perl(Module::Install::Base)"
yum install -y "perl(Template)"
yum install -y "perl(CGI::Simple::Cookie)"
yum install -y "perl(Class::Inspector)"
yum install -y "perl(Data::Dump)"
yum install -y "perl(Devel::InnerPackage)"
yum install -y "perl(Module::Build)"
yum install -y "perl(Module::Pluggable::Object)"
yum install -y "perl(Path::Class)"
yum install -y "perl(Path::Class::Dir)"
yum install -y "perl(Path::Class::File)"
yum install -y "perl(Tree::Simple)"

################################################################################
# must be installed together: and conflict with moose
wget -q "http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Catalyst-Devel-1.08-1.el5.rf.noarch.rpm"
wget -q "http://dag.wieers.com/rpm/packages/perl-Catalyst-Runtime/perl-Catalyst-Runtime-5.7015-1.el5.rf.noarch.rpm"
rpm -Uvh perl-Catalyst-Devel-1.08-1.el5.rf.noarch.rpm perl-Catalyst-Runtime-5.7015-1.el5.rf.noarch.rpm
################################################################################

try "http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Catalyst-Plugin-Session-State-Cookie-0.09-1.el5.rf.noarch.rpm"
try "http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Catalyst-Plugin-Session-0.29-1.el5.rf.noarch.rpm"
yum install -y "perl(Cache::FastMmap)"
try "http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Catalyst-Plugin-Session-Store-FastMmap-0.13-1.el5.rf.noarch.rpm"

try http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-MIME-Types-1.28-1.el5.rf.noarch.rpm
try http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-namespace-autoclean-0.09-1.el5.rf.noarch.rpm
yum install -y "perl(Carp::Clan)"
# try http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-MooseX-Types-0.21-1.el5.rf.noarch.rpm
#     perl(Moose) >= 0.93 is needed by perl-MooseX-Types-0.21-1.el5.rf.noarch
try http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-MooseX-Types-0.17-1.el5.rf.noarch.rpm

try "http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Catalyst-Plugin-Static-Simple-0.28-1.el5.rf.noarch.rpm"
try http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Set-Object-1.27-1.el5.rf.i386.rpm
try http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-UNIVERSAL-isa-1.03-1.el5.rf.noarch.rpm
try http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Catalyst-Plugin-Authentication-0.10016-1.el5.rf.noarch.rpm
try http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Catalyst-Plugin-Authorization-Roles-0.08-1.el5.rf.noarch.rpm
try http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Config-Any-0.21-1.el5.rf.noarch.rpm
try http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Test-use-ok-0.02-1.el5.rf.noarch.rpm
try http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Tie-ToObject-0.03-1.el5.rf.noarch.rpm

yum install -y "perl(Task::Weaken)"
try http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Data-Visitor-0.27-1.el5.rf.noarch.rpm
try http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Catalyst-Plugin-ConfigLoader-0.27-1.el5.rf.noarch.rpm
EOF

wd setup --to=redwood.lab

ssh root@redwood.lab "(cd /usr/share/pkild/; bin/local_config)"
ssh root@redwood.lab "/etc/init.d/httpd resstart"

################################################################################
# # RPM::Specfile builds broken packages
# yum install -y rpm-devel rpm-build
# wget http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-RPM-Specfile-1.51-1.el5.rf.noarch.rpm
# rpm -Uvh perl-RPM-Specfile-1.51-1.el5.rf.noarch.rpm 
# wget http://search.cpan.org/CPAN/authors/id/A/AG/AGRUNDMA/Catalyst-Plugin-RequireSSL-0.06.tar.gz
# cpanflute2 Catalyst-Plugin-RequireSSL-0.06.tar.gz 
# rpm -Uvh perl-Catalyst-Plugin-RequireSSL-0.06-8.src.rpm
# rpmbuild -ba /usr/src/redhat/SPECS/perl-Catalyst-Plugin-RequireSSL.spec 
# rpm -Uvh /usr/src/redhat/RPMS/noarch/perl-Catalyst-Plugin-RequireSSL-0.06-8.noarch.rpm


################################################################################
# # Requires Catalyst/Engine/Apache2/MP20.pm which is in Catalyst-Engine-Apache 
# #    which needs ExtUtils::MakeMaker version 6.31 to build
# #        which  won't install without force
#wget http://ftp.arix.com/cpan2rpm-2.028-1.noarch.rpm
#rpm -Uvh cpan2rpm-2.028-1.noarch.rpm 
#yum install -y "perl(Test::Pod::Coverage)"
#wget http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-HTTP-Request-AsCGI-1.2-1.el5.rf.noarch.rpm
#rpm -Uvh perl-HTTP-Request-AsCGI-1.2-1.el5.rf.noarch.rpm
#cpan2rpm --no-sign --author "Andy Grundman" --version "0.06" Catalyst::Plugin::RequireSSL
#rpm -Uvh /usr/src/redhat/RPMS/noarch/perl-Catalyst-Plugin-RequireSSL-0.06-1.noarch.rpm
#
#cat<<EOF | perl -MCPAN -eshell
#install M/MS/MSCHWERN/ExtUtils-MakeMaker-6.54.tar.gz 
#EOF
#  # won't install without force

# jd;slkfja;lkj;alsdkjf;dsflj dfssakjafsd this shit is so ghetto


################################################################################
# # Just trying to get base functionality back...
# #    
# catalyst.pl myApp
# cd myApp
# ./script/myapp_server.pl

yum install -y "perl(Config::General)"
try http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-parent-0.221-1.el5.rf.noarch.rpm
cpan2rpm --no-sign "Config::General"
rpm -Uvh /usr/src/redhat/RPMS/i386/perl-Config-General-2.50-1.i386.rpm
wget http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Catalyst-Action-RenderView-0.14-1.el5.rf.noarch.rpm
rpm -Uvh perl-Catalyst-Action-RenderView-0.14-1.el5.rf.noarch.rpm

wget http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Template-Timer-1.00-1.el5.rf.noarch.rpm
rpm -Uvh perl-Template-Timer-1.00-1.el5.rf.noarch.rpm
wget http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Catalyst-View-TT-0.31-1.el5.rf.noarch.rpm
rpm -Uvh perl-Catalyst-View-TT-0.31-1.el5.rf.noarch.rpm 
# ./script/pkild_create.pl view TT TT

wget http://apt.sw.be/redhat/el5/en/i386/dag/RPMS/perl-Catalyst-Model-File-0.06-1.el5.rf.noarch.rpm
perl-Catalyst-Model-File-0.06-1.el5.rf.noarch.rpm
cpan2rpm --no-sign Catalyst::Component::InstancePerContext
rpm -Uvh /usr/src/redhat/RPMS/noarch/perl-Catalyst-Component-InstancePerContext-0.001001-1.noarch.rpm
# ./script/pkild_create.pl model File File "/tmp"

